##########################################################################################
#    _____                                      _    _       _            _              #
#   / ____|                                    | |  | |     | |          | |             #
#  | (___  _ __   __ ___      ___ __   ___ _ __| |  | |_ __ | | ___   ___| | _____ _ __  #
#   \___ \| '_ \ / _` \ \ /\ / / '_ \ / _ \ '__| |  | | '_ \| |/ _ \ / __| |/ / _ \ '__| #
#   ____) | |_) | (_| |\ V  V /| | | |  __/ |  | |__| | | | | | (_) | (__|   <  __/ |    #
#  |_____/| .__/ \__,_| \_/\_/ |_| |_|\___|_|   \____/|_| |_|_|\___/ \___|_|\_\___|_|    #
#         | |                                                                            #
#         |_|                                                                            #
#                                   v${version} by Biscut                                        #
##########################################################################################

# Choose what currency it uses to level up. Options: 'XPLEVELS', 'MONEY', 'XP'
# NOTE: MONEY requires Vault (plugin)!
currency: 'XPLEVELS'

# List your spawners and XP levels here
spawners:
  1: # Spawner level 1
    mobs: # List of mobs
    - 'COW'
    - 'ZOMBIE'
    cost: 10 # How many XP levels, money, or XP it costs to upgrade to this level
  2:
    mobs:
    - 'BLAZE'
    cost: 20

# List your spawners here that you would like players to unlock at level 0
default-spawners:
  - 'SPIDER'

# Write command aliases here for /spawnerrankup, so players don't need to type a huge command
spawnerrankup-aliases:
  - 'sru'

rankup-gui:
  enabled: true
  rows: 3
  confirm-item: 'WOOL:5'
  confirm-name: '&aCONFIRM'
  confirm-lore-regular: # Placeholders: {level}, {nextlevel}, {nextlevelcost}
  - '&7Level &e{level} &7-> level &e{nextlevel}'
  - '&7Cost: &e{nextlevelcost} XP levels'
  confirm-lore-max:
  - '&7MAX LEVEL'
  confirm-slots:
    - 12
    - 13
    - 14
  cancel-item: 'WOOL:14'
  cancel-name: '&cDENY'
  cancel-lore: []
  cancel-slots:
    - 26
  fill-item: 'AIR'
  fill-name: ''
  fill-lore: []
  title: '&7CONFIRM UPGRADE' # Please do not leave leave any of these below texts empty ('') please
  confirm-sound-enabled: false
  confirm-sound: 'random.levelup'
  confirm-volume: 1.0
  confirm-pitch: 1.0
  # Sound when the cancel block is clicked
  cancel-sound-enabled: false
  cancel-sound: 'mob.villager.hit'
  cancel-volume: 1.0
  cancel-pitch: 1.0


# The level that players start at (can only go below default using /su setlevel <player> <level>)
default-level: 0

messages:
  no-permission-command: '&cNo permission!'
  cannot-place: '&cYou cannot place this mob!'
  insufficient-level: '&cYou cannot place this mob yet! You can unlock {spawner} spawners at level {level}!' # Placeholders: {level}, {spawner}
  insufficient-currency: '&cYou do not have enough XP levels! You need {costremaining} more XP level(s) to rankup to level {nextlevel}!' # Placeholders: {costremaining}, {nextlevel}, {nextlevelcost}
  max-level: '&cYou are already max level!'
  rankup: '&aYou are now level {level}!' # Placeholders: {level}, {previouslevel}
  level: '&aYou are currently spawner level {level}.' # Placeholders: {level}
  gui-cancel: '&aYou have canceled the rankup.'

# How often should the server save the levels config? (in seconds)
save-interval: 300

# Please do not change #
config-version: 1